// dummyData.js

let games = [
	{
		id: '1',
		title: 'The Legend of Zelda: Tears of the Kingdom',
		platform: ['Nintendo Switch'],
		publisherId: '1',
	},
	{
		id: '2',
		title: 'Elden Ring',
		platform: ['PlayStation 5', 'Xbox Series X', 'PC'],
		publisherId: '2',
	},
	{
		id: '3',
		title: 'God of War: Ragnarök',
		platform: ['PlayStation 4', 'PlayStation 5'],
		publisherId: '3',
	},
	{
		id: '4',
		title: 'Hades',
		platform: ['PC', 'Nintendo Switch', 'PlayStation 5', 'Xbox One'],
		publisherId: '4',
	},
	{
		id: '5',
		title: 'Cyberpunk 2077',
		platform: ['PC', 'PlayStation 5', 'Xbox Series X'],
		publisherId: '5',
	},
	{
		id: '6',
		title: 'Stardew Valley',
		platform: ['PC', 'Nintendo Switch', 'Mobile'],
		publisherId: '6',
	},
	{
		id: '7',
		title: 'The Witcher 3: Wild Hunt',
		platform: ['PC', 'PlayStation 5', 'Xbox Series X'],
		publisherId: '5',
	},
	{
		id: '8',
		title: 'Minecraft',
		platform: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
		publisherId: '8',
	},
	{
		id: '9',
		title: 'Red Dead Redemption 2',
		platform: ['PC', 'PlayStation 5', 'Xbox Series X'],
		publisherId: '7',
	},
	{
		id: '10',
		title: 'Baldur’s Gate 3',
		platform: ['PC', 'PlayStation 5', 'Mac'],
		publisherId: '9',
	},
	{
		id: '11',
		title: 'Starfield',
		platform: ['PC', 'Xbox Series X'],
		publisherId: '10',
	},
	{
		id: '12',
		title: 'Horizon Forbidden West',
		platform: ['PlayStation 4', 'PlayStation 5'],
		publisherId: '11',
	},
	{
		id: '13',
		title: 'Sea of Stars',
		platform: ['PC', 'Nintendo Switch', 'PlayStation 5', 'Xbox Series X'],
		publisherId: '12',
	},
	{
		id: '14',
		title: 'Disco Elysium',
		platform: ['PC', 'PlayStation 5', 'Xbox Series X'],
		publisherId: '13',
	},
	{
		id: '15',
		title: 'Return of the Obra Dinn',
		platform: ['PC', 'Nintendo Switch', 'PlayStation 4', 'Xbox One'],
		publisherId: '14',
	},
	{
		id: '16',
		title: 'Outer Wilds',
		platform: ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
		publisherId: '15',
	},
];

let authors = [
	{ id: '1', name: 'Jane Doe', verified: true },
	{ id: '2', name: 'John Smith', verified: false },
	{ id: '3', name: 'Emily Carter', verified: true },
	{ id: '4', name: 'Michael Brown', verified: false },
	{ id: '5', name: 'Sophia Turner', verified: true },
	{ id: '6', name: 'Liam Johnson', verified: false },
	{ id: '7', name: 'Olivia White', verified: true },
	{ id: '8', name: 'Noah Green', verified: false },
	{ id: '9', name: 'Ava Martinez', verified: true },
	{ id: '10', name: 'Ethan Lewis', verified: true },
	{ id: '11', name: 'Harper Collins', verified: false },
	{ id: '12', name: 'Mason Rivera', verified: true },
	{ id: '13', name: 'Isabella Brooks', verified: false },
	{ id: '14', name: 'Lucas Kim', verified: true },
	{ id: '15', name: 'Amelia Patel', verified: true },
	{ id: '16', name: 'Sebastian Flores', verified: false },
];

let reviews = [
	{
		id: '1',
		rating: 9,
		content:
			'An incredible open-world experience with unmatched attention to detail.',
		authorId: '1',
		gameId: '1',
	},
	{
		id: '2',
		rating: 10,
		content: 'A masterpiece — rich storytelling and challenging combat.',
		authorId: '2',
		gameId: '2',
	},
	{
		id: '3',
		rating: 8,
		content:
			'Beautiful art direction and fluid gameplay, but a bit repetitive at times.',
		authorId: '3',
		gameId: '3',
	},
	{
		id: '4',
		rating: 7,
		content: 'Solid mechanics, though the pacing could be better.',
		authorId: '4',
		gameId: '4',
	},
	{
		id: '5',
		rating: 6,
		content: 'Good foundation but too many bugs at launch.',
		authorId: '5',
		gameId: '5',
	},
	{
		id: '6',
		rating: 9,
		content: 'Relaxing and wholesome; perfect for winding down.',
		authorId: '6',
		gameId: '6',
	},
	{
		id: '7',
		rating: 10,
		content: 'An epic story with phenomenal voice acting.',
		authorId: '7',
		gameId: '7',
	},
	{
		id: '8',
		rating: 8,
		content: 'Creative gameplay with tons of replay value.',
		authorId: '8',
		gameId: '8',
	},
	{
		id: '9',
		rating: 9,
		content: 'Visually stunning with a deeply emotional narrative.',
		authorId: '9',
		gameId: '9',
	},
	{
		id: '10',
		rating: 7,
		content: 'Entertaining but lacks long-term depth.',
		authorId: '10',
		gameId: '10',
	},
	{
		id: '11',
		rating: 8,
		content: 'Ambitious sci-fi with impressive scope and exploration.',
		authorId: '11',
		gameId: '11',
	},
	{
		id: '12',
		rating: 9,
		content: 'Stunning visuals and a strong continuation of Aloy’s story.',
		authorId: '12',
		gameId: '12',
	},
	{
		id: '13',
		rating: 9,
		content: 'A love letter to classic RPGs with gorgeous pixel art.',
		authorId: '13',
		gameId: '13',
	},
	{
		id: '14',
		rating: 10,
		content: 'Narrative masterpiece with unforgettable characters.',
		authorId: '14',
		gameId: '14',
	},
	{
		id: '15',
		rating: 8,
		content: 'Unique mystery that rewards careful observation.',
		authorId: '15',
		gameId: '15',
	},
	{
		id: '16',
		rating: 10,
		content: 'Mind-bending exploration with a satisfying time-loop payoff.',
		authorId: '16',
		gameId: '16',
	},
	{
		id: '17',
		rating: 8,
		content: 'Follow-up impressions show the adventure still feels fresh.',
		authorId: '1',
		gameId: '2',
	},
	{
		id: '18',
		rating: 9,
		content: 'After more hours, the combat depth really shines.',
		authorId: '2',
		gameId: '3',
	},
	{
		id: '19',
		rating: 7,
		content: 'Replay reminded me how atmospheric the world can be.',
		authorId: '3',
		gameId: '4',
	},
	{
		id: '20',
		rating: 8,
		content: 'Multiplayer sessions added surprising longevity.',
		authorId: '4',
		gameId: '5',
	},
	{
		id: '21',
		rating: 9,
		content: 'Post-patch experience is dramatically smoother.',
		authorId: '5',
		gameId: '6',
	},
	{
		id: '22',
		rating: 10,
		content: 'The cozy charm keeps pulling me back in nightly.',
		authorId: '6',
		gameId: '7',
	},
	{
		id: '23',
		rating: 9,
		content: 'New game plus highlights just how epic the story is.',
		authorId: '7',
		gameId: '8',
	},
	{
		id: '24',
		rating: 8,
		content: 'Creative blocks sparked by its sandbox tools.',
		authorId: '8',
		gameId: '9',
	},
	{
		id: '25',
		rating: 9,
		content: 'Photo mode reveals details I missed the first time.',
		authorId: '9',
		gameId: '10',
	},
	{
		id: '26',
		rating: 7,
		content: 'Multiplayer heists offer chaotic fun in short bursts.',
		authorId: '10',
		gameId: '11',
	},
	{
		id: '27',
		rating: 8,
		content: 'Exploration keeps uncovering hidden narrative threads.',
		authorId: '11',
		gameId: '12',
	},
	{
		id: '28',
		rating: 9,
		content: 'Side quests pack emotional punches on repeat playthroughs.',
		authorId: '12',
		gameId: '13',
	},
	{
		id: '29',
		rating: 8,
		content: 'Retro inspirations continue to delight.',
		authorId: '13',
		gameId: '14',
	},
	{
		id: '30',
		rating: 10,
		content: 'Second ending proved even more powerful than the first.',
		authorId: '14',
		gameId: '15',
	},
	{
		id: '31',
		rating: 9,
		content: 'Puzzle variety keeps the experience sharp.',
		authorId: '15',
		gameId: '16',
	},
	{
		id: '32',
		rating: 10,
		content: 'Time-loop secrets reward patience and curiosity.',
		authorId: '16',
		gameId: '1',
	},
	{
		id: '33',
		rating: 9,
		content: 'Weekly challenges breathe new life into the campaign.',
		authorId: '1',
		gameId: '6',
	},
	{
		id: '34',
		rating: 8,
		content: 'Lore hunting runs prove endlessly satisfying.',
		authorId: '2',
		gameId: '8',
	},
	{
		id: '35',
		rating: 9,
		content: 'Combat builds feel distinct on every replay.',
		authorId: '3',
		gameId: '10',
	},
	{
		id: '36',
		rating: 7,
		content: 'Co-op chaos creates unforgettable moments.',
		authorId: '4',
		gameId: '12',
	},
	{
		id: '37',
		rating: 8,
		content: 'Story DLC cements it as a modern classic.',
		authorId: '5',
		gameId: '14',
	},
	{
		id: '38',
		rating: 10,
		content: 'Seasonal updates keep the farm life engaging.',
		authorId: '6',
		gameId: '16',
	},
	{
		id: '39',
		rating: 9,
		content: 'Endgame trials showcase superb boss design.',
		authorId: '7',
		gameId: '2',
	},
	{
		id: '40',
		rating: 8,
		content: 'Procedural worlds still surprise after dozens of hours.',
		authorId: '8',
		gameId: '4',
	},
	{
		id: '41',
		rating: 10,
		content: 'Character arcs endure as some of the finest in gaming.',
		authorId: '9',
		gameId: '6',
	},
	{
		id: '42',
		rating: 8,
		content: 'Heist planning remains tense and rewarding.',
		authorId: '10',
		gameId: '8',
	},
	{
		id: '43',
		rating: 9,
		content: 'Base building scratches that sci-fi survival itch.',
		authorId: '11',
		gameId: '10',
	},
	{
		id: '44',
		rating: 8,
		content: 'Skill trees encourage wildly different play styles.',
		authorId: '12',
		gameId: '12',
	},
	{
		id: '45',
		rating: 9,
		content: 'Old-school charm mixes well with modern polish.',
		authorId: '13',
		gameId: '13',
	},
	{
		id: '46',
		rating: 10,
		content: 'Investigation twists kept me glued until the finale.',
		authorId: '14',
		gameId: '15',
	},
	{
		id: '47',
		rating: 8,
		content: 'Minimalist art direction still feels striking.',
		authorId: '15',
		gameId: '3',
	},
	{
		id: '48',
		rating: 10,
		content: 'Quantum puzzles reward every careful observation.',
		authorId: '16',
		gameId: '5',
	},
];

let publishers = [
	{ id: '1', name: 'Nintendo' },
	{ id: '2', name: 'FromSoftware' },
	{ id: '3', name: 'Santa Monica Studio' },
	{ id: '4', name: 'Supergiant Games' },
	{ id: '5', name: 'CD Projekt Red' },
	{ id: '6', name: 'ConcernedApe' },
	{ id: '7', name: 'Rockstar Games' },
	{ id: '8', name: 'Mojang Studios' },
	{ id: '9', name: 'Larian Studios' },
	{ id: '10', name: 'Bethesda Game Studios' },
	{ id: '11', name: 'Guerrilla Games' },
	{ id: '12', name: 'Sabotage Studio' },
	{ id: '13', name: 'ZA/UM' },
	{ id: '14', name: '3909 LLC' },
	{ id: '15', name: 'Annapurna Interactive' },
];

export default { games, reviews, authors, publishers };
